targets:
  $default:
    builders:
      # Drift — génération des classes de la DB SQLite
      drift_dev:
        options:
          store_date_time_values_as_text: true

      # JSON serializable
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
