services:
  db:
    image: postgres:16-alpine
    container_name: babicash_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: babicash
      POSTGRES_PASSWORD: babicash
      POSTGRES_DB: babicash
    ports:
      - "5432:5432"
    volumes:
      - babicash_pgdata:/var/lib/postgresql/data

volumes:
  babicash_pgdata:
