"""add_caissier_id_to_ventes

Revision ID: 6d82daa25258
Revises: 8d5b7a78546a
Create Date: 2026-07-09 01:01:20.353817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d82daa25258'
down_revision: Union[str, None] = '8d5b7a78546a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventes', sa.Column('caissier_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'ventes', 'users', ['caissier_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ventes', type_='foreignkey')
    op.drop_column('ventes', 'caissier_id')
    # ### end Alembic commands ###
