"""uq_tiers_boutique_telephone

Revision ID: 8d5b7a78546a
Revises: 0004
Create Date: 2026-07-08 18:45:04.517648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5b7a78546a'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Dédupliquer (boutique_id, telephone) : relier les ventes vers le doublon retenu puis supprimer
    op.execute("""
        WITH keepers AS (
            SELECT DISTINCT ON (boutique_id, telephone) id AS keep_id, boutique_id, telephone
            FROM comptes_tiers
            WHERE telephone IS NOT NULL
            ORDER BY boutique_id, telephone, id
        ),
        duplicates AS (
            SELECT ct.id AS dup_id, k.keep_id
            FROM comptes_tiers ct
            JOIN keepers k ON k.boutique_id = ct.boutique_id AND k.telephone = ct.telephone
            WHERE ct.id <> k.keep_id
        )
        UPDATE ventes SET tier_id = d.keep_id
        FROM duplicates d WHERE ventes.tier_id = d.dup_id
    """)
    op.execute("""
        DELETE FROM comptes_tiers
        WHERE id IN (
            SELECT id FROM (
                SELECT id,
                       ROW_NUMBER() OVER (PARTITION BY boutique_id, telephone ORDER BY id) AS rn
                FROM comptes_tiers
                WHERE telephone IS NOT NULL
            ) t WHERE rn > 1
        )
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_abonnements_proprietaire_id'), table_name='abonnements', if_exists=True)
    op.create_unique_constraint('uq_tiers_boutique_telephone', 'comptes_tiers', ['boutique_id', 'telephone'])
    op.alter_column('sessions_caisse', 'montant_final_declare',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('sessions_caisse', 'statut',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions_caisse', 'statut',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('sessions_caisse', 'montant_final_declare',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_constraint('uq_tiers_boutique_telephone', 'comptes_tiers', type_='unique')
    op.create_index(op.f('ix_abonnements_proprietaire_id'), 'abonnements', ['proprietaire_id'], unique=False)
    # ### end Alembic commands ###
