"""add_statut_date_retour_to_ventes

Revision ID: d36b710d125f
Revises: 6d82daa25258
Create Date: 2026-07-09 02:01:03.967466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36b710d125f'
down_revision: Union[str, None] = '6d82daa25258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventes', sa.Column('statut', sa.String(length=20), nullable=False, server_default='ACTIVE'))
    op.add_column('ventes', sa.Column('date_retour', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventes', 'date_retour')
    op.drop_column('ventes', 'statut')
    # ### end Alembic commands ###
